version: "3.9"

services:
  isyshell-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: isyshell-api
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      ISY_TOKEN: ${ISY_TOKEN:-meu-token-seguro-trocar-em-producao} # apenas para desenvolvimento local
      SCRIPTS_DIR: /opt/isyone/scripts
      DB_PATH: /data/isyshell.db
      SCRIPT_TIMEOUT: 120
    volumes:
      - ./scripts:/opt/isyone/scripts:ro
      - isyshell_data:/data

volumes:
  isyshell_data:
    driver: local
